# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: ubuntu-latest

  variables:
    - group: uao
    - name: imageName
      value: "uao"
    - name: azureSuscription
      value: "SCRGAPICONSTRUCTORPRD"
    - name: azureRegistry
      value: ""


steps:

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      jdkVersionOption: '1.17'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean install'
      sonarQubeRunAnalysis: true
    displayName: 'Maven Install'

  - task: Docker@1
      inputs:
        command: 'Build an image'
        azureSubscriptionEndpoint: $(azureSuscription)
        azureContainerRegistry: $(azureRegistry)
        imageName: $(imageName):$(Build.BuildId)
        includeSourceTags: true
        includeLatestTag: true
      displayName: Build Docker image

  - task: Docker@1
      inputs:
        command: 'Push an image'
        azureSubscriptionEndpoint: $(azureSuscription)
        azureContainerRegistry: $(azureRegistry)
        imageName: $(imageName):latest
      displayName: Push Docker with latest tag
